### ISSUE TITLE
FAIL: parallel_workers/parallel_workers

### ISSUE THREAD

**Issue by ramet** [starpu-runtime/starpu#44]
### Steps to reproduce

I'm using a clean Debian 12 ARM system in a virtual machine (which exposes 2 cores) under MacOS.
StarPU is installed using Guix in the requested configuration for PaStiX 6.3.2.

Some tests related to parallel workers are failing.
Perhaps the problem is more in HWLOC?

### Obtained behavior

Here is the command line : 
```sh
guix shell gcc-toolchain coreutils pastix --pure -- /bin/bash --norc 
```
The error occurs when installing the dependency on StarPU 1.4.4, during unit testing : "FAIL: parallel_workers/parallel_workers"
(same error with : "FAIL: parallel_workers/parallel_workers_oldapi")

### Configuration result

```
FAIL: parallel_workers/parallel_workers
=======================================

[starpu][localhost][_perf_model_add_dir] Warning: directory </gnu/store/i68nyhxx1bh1r3amzs503mcy3b02gf97-starpu-1.4.4/share/starpu/perfmodels/sampling> as set by installation directory does not exist
hwloc/linux: failed to find sysfs cpu topology directory, aborting linux discovery.
[starpu][localhost][_starpu_init_topology] Warning: The OS did not report CPU cores. Assuming there is only one hardware thread per core.
[error] `./parallel_workers/parallel_workers' killed with signal 11; test marked as failed
while looking for core file of ./parallel_workers/parallel_workers: core.102544: No such file or directory

warning: core file may not match specified executable file.
[New LWP 102544]
[New LWP 102560]
[New LWP 102558]
[New LWP 102559]
[New LWP 102561]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libthread_db.so.1".
Core was generated by `/tmp/guix-build-starpu-1.4.4.drv-0/source/examples/parallel_workers/.libs/paral'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  starpu_sched_ctx_create (workerids=0x0, nworkers=1, sched_ctx_name=sched_ctx_name@entry=0xfffff7ec0b48 "parallel_workers") at core/sched_ctx.c:793
793			if (workerids[i] < 0 || workerids[i] >= num_workers)
[Current thread is 1 (Thread 0xfffff7ff1020 (LWP 102544))]
warning: File "/gnu/store/vwkiblwq7y8xiflg51cnk2a3x1wwiysj-gcc-11.3.0-lib/lib/libstdc++.so.6.0.29-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /gnu/store/vwkiblwq7y8xiflg51cnk2a3x1wwiysj-gcc-11.3.0-lib/lib/libstdc++.so.6.0.29-gdb.py
line to your configuration file "/tmp/guix-build-starpu-1.4.4.drv-0/source/.config/gdb/gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/tmp/guix-build-starpu-1.4.4.drv-0/source/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
Undefined command: "py-list".  Try "help".
Undefined command: "starpu-tasks".  Try "help".
Undefined command: "starpu-workers".  Try "help".
Undefined command: "starpu-print-datas-summary".  Try "help".
Undefined command: "starpu-memusage".  Try "help".
Undefined command: "starpu-print-archs".  Try "help".
Undefined command: "starpu-print-registered-models".  Try "help".
#0  starpu_sched_ctx_create (workerids=0x0, nworkers=1, sched_ctx_name=sched_ctx_name@entry=0xfffff7ec0b48 "parallel_workers") at core/sched_ctx.c:793
        __func__ = "starpu_sched_ctx_create"
        varg_list = {__stack = 0xfffffffebbd0, __gr_top = 0xfffffffebbd0, __vr_top = 0xfffffffebba0, __gr_offs = -32, __vr_offs = 0}
        arg_type = -135262208
        min_prio_set = 0
        max_prio_set = 0
        min_prio = 0
        max_prio = 0
        nsms = 0
        sub_ctxs = 0x0
        nsub_ctxs = 0
        user_data = 0x0
        sched_policy = 0x0
        hierarchy_level = 0
        nesting_sched_ctx = 10
        awake_workers = 0
        init_sched = 0x0
        num_workers = 4
        i = 0
        sched_ctx = <optimized out>
        added_workerids = 0x42e070
        nw_ctx = <optimized out>
        p_ret = <optimized out>
        __ptrs = <optimized out>
        __n = <optimized out>
#1  0x0000fffff7e8c214 in _starpu_parallel_worker_create (parallel_worker=parallel_worker@entry=0x42c3b0) at parallel_worker/starpu_parallel_worker_create.c:333
        config = <optimized out>
#2  0x0000fffff7e8c3f4 in _starpu_parallel_worker_group_create (group=group@entry=0x42c2f0) at parallel_worker/starpu_parallel_worker_create.c:350
        c = 0x42c3b0
#3  0x0000fffff7e8d590 in _starpu_parallel_worker_config (parallel_worker_level=<optimized out>, machine=0x42c270) at parallel_worker/starpu_parallel_worker_create.c:553
        g = 0x42c2f0
        ret = 0
        config = <optimized out>
        sched_policy = <optimized out>
        global_ctx = <optimized out>
#4  0x0000fffff7e8d7ec in _starpu_parallel_worker_init_varg (parallel_worker_level=parallel_worker_level@entry=HWLOC_OBJ_PACKAGE, varg_list=...) at parallel_worker/starpu_parallel_worker_create.c:241
        arg_type = 0
        machine = 0x42c270
        __func__ = "_starpu_parallel_worker_init_varg"
        __PRETTY_FUNCTION__ = "_starpu_parallel_worker_init_varg"
#5  0x0000fffff7e8e058 in starpu_parallel_worker_init (parallel_worker_level=parallel_worker_level@entry=HWLOC_OBJ_PACKAGE) at parallel_worker/starpu_parallel_worker_create.c:255
        config = <optimized out>
        varg_list = {__stack = 0xfffffffebea0, __gr_top = 0xfffffffebea0, __vr_top = 0xfffffffebe60, __gr_offs = -56, __vr_offs = -128}
#6  0x0000000000400ff8 in main () at parallel_workers/parallel_workers.c:79
        ntasks = 8
        ret = 0
        i = <optimized out>
        parallel_workers = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        __func__ = "main"
        array1 = {0 <repeats 4000 times>}
        array2 = {0 <repeats 3000 times>, 1.3906711614409153e-309, 1.3906704974653626e-309, 1.3906711614411525e-309, 1.3906704983826054e-309, 0, 0, 1.3906711614613894e-309, 1.3906704975785234e-309, 1.3906704984230793e-309, 1.3906704983826054e-309, 1.3906704984275061e-309, 0, 1.0239368235597433e+200, 5.0130396337438505e-90, 8.3365299802249716e-72, 3.6195066075658384e+262, 1.1146009660511128e+171, 2.2120874227700783e+214, 1.1746884519525608e+214, 3.7879995910192795e+209, 1.1711897052348906e+166, 1.9108618774865702e+214, 3.5591190367735002e+180, 1.46016160971922e-319, 0 <repeats 377 times>, 7.7305068220971491e-318, 7.7112580245351742e-318, 7.7112580245351742e-318, 3.2379086165851934e-319, 0, 2.4703282292062327e-323, 8.034060754902011e-318, 8.1554823280239558e-318, 8.1439409545371042e-318, 8.3982464237645107e-318, 3.2379086165851934e-319, 7.7102698932434917e-318, 1.4821969375237396e-323, 0 <repeats 15 times>, 1.2142157312194475e-318, 1.2024767314742595e-318, 1.2024767314742595e-318, 0, 4.0473857707314917e-319, 3.860826582861837e-319, 3.860826582861837e-319, 1.3906711614580693e-309, 1.390670497321886e-309, 1.3906711614586226e-309, 1.3906704983969926e-309, 1.3906711614593341e-309, 1.3906704973289412e-309, 1.3906711614586226e-309, 4.9406564584124654e-323, 1.3906711614584645e-309, 1.3906704974401455e-309, 1.3906704982485357e-309, 2.3221085354538588e-322, 1.3906711614593341e-309, 1.3906704973293563e-309, 1.390671161459255e-309, 1.3906704973530912e-309, 1.390671161459255e-309, 1.3906704973666879e-309, 0, 0, 2.0733533996918329e-317, 1.3906711614622194e-309, 1.390671161459255e-309, 1.3906704973663124e-309, 1.3906704566746112e-309, 1.3906704983969926e-309, 0, 1.3906704982545041e-309, 1.3906704650931736e-309, 1.3906704983969926e-309, 0, 1.3906704982475476e-309, 1.3906704660645462e-309, 1.3906704983969926e-309, 1.3906711614611522e-309, 1.3906704973779723e-309, 2.0733533996918329e-317, 0, 1.3906704984275061e-309, 0, 4.9406564584124654e-324, 1.3906711614622194e-309, 1.3906704984028423e-309, 1.3906704983826054e-309, 0, 1.390670497266353e-309, 1.3906704983623685e-309, 1.3906711614622589e-309, 1.3906704650725415e-309, 1.3906711614622589e-309, 1.3906704650725415e-309, 9.8813129168249309e-324, 1.3906711614622589e-309, 1.3906711614590179e-309, 9.8813129168249309e-324, 0, 1.4821969375237396e-323, 1.3906704984253717e-309, 1.3906711614625751e-309, 0, 1.3906704984028423e-309, 2.9643938750474793e-323, 3.2127112686472898e-319, 5.2917543283166305e-318, 3.2127112686472898e-319, 5.2917543283166305e-318, 4.2440079518075883e-314, 0, 0, 0, 9.7773615049399326e-318, 2.0236928853657458e-320, 1.3906711614609941e-309, 1.3906704973765889e-309, 1.3906704572715759e-309, 0, 0, 8.4617375499254853e-315, 1.3906711614662115e-309, 1.3906704972666494e-309, 1.390671161470994e-309, 1.3906704984230793e-309, 1.390670464783849e-309, 1.3906704984275061e-309, 1.3906704982485357e-309, 4.9406564584124654e-324, 0, 1.3906711614712707e-309, 0, 1.390670497266353e-309, 0, 0, 0, 1.390670497266353e-309, 0, 1.3906704984324467e-309, 0, 0, 0, 4.9406564584124654e-323, 0, 0, 0, 6.9169190417774516e-323, 0, 0, 1.3906704982481405e-309, 1.3906711614820216e-309, 0, 4.1106261733991712e-321, 3.3280039514459023e-294, 0, 2.1279211652158202e-314, 7.9595951807608183e-319, 3.1620201333839779e-322, 9.7564921720595984e-318, 1.3350986381965695e-307, 1.8914248227666973e-307, 8.4879831668254831e-314, 3.1620201333839779e-322, 3.1620201333839779e-322, 3.1620201333839779e-322, 2.7667676167109806e-321, 2.7667676167109806e-321, 3.9525251667299724e-323, 8.4879831653432862e-314...}
        handle1 = 0x0
        handle2 = 0x0
        size = 0
        out = <optimized out>
Undefined command: "py-bt".  Try "help".

Thread 5 (Thread 0xfffff5fbf080 (LWP 102561)):
#0  0x0000fffff786ebe8 in __pthread_mutex_unlock_usercnt () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.
#1  0x0000fffff7e15b98 in _starpu_worker_relax_on () at ./core/workers.h:1118
        p_ret = <optimized out>
        worker = 0xfffff7f05308 <_starpu_config+15960>
        __func__ = "_starpu_worker_relax_on"
        __PRETTY_FUNCTION__ = "_starpu_worker_relax_on"
#2  0x0000fffff7e16594 in ws_pop_task (sched_ctx_id=0) at sched_policies/work_stealing_policy.c:601
        ws = 0x428c30
        task = <optimized out>
        workerid = 3
        victim = <optimized out>
#3  0x0000fffff7e04f88 in _starpu_pop_task (worker=worker@entry=0xfffff7f05308 <_starpu_config+15960>) at core/sched_policy.c:1020
        sched_ctx = 0xfffff7fa1600 <_starpu_config+655696>
        task = 0x0
        worker_id = <optimized out>
        node = <optimized out>
        profiling = 0
        pop_start_time = {tv_sec = 281474841465896, tv_nsec = 0}
        pick = <optimized out>
        i = <optimized out>
        nbuffers = <optimized out>
#4  0x0000fffff7e2ab30 in _starpu_get_worker_task (worker=worker@entry=0xfffff7f05308 <_starpu_config+15960>, workerid=workerid@entry=3, memnode=memnode@entry=0) at drivers/driver_common/driver_common.c:431
        task = <optimized out>
        keep_awake = <optimized out>
        __func__ = "_starpu_get_worker_task"
#5  0x0000fffff7e8a1bc in _starpu_cpu_driver_run_once (cpu_worker=cpu_worker@entry=0xfffff7f05308 <_starpu_config+15960>) at drivers/cpu/driver_cpu.c:608
        memnode = 0
        workerid = 3
        pi = {conf = 0x0, event_type = starpu_prof_tool_event_driver_init_end, starpu_version = {1, 4126926560, 65535}, thread_id = -135748100, worker_id = 65535, device_number = -135245048, driver_type = 65535, memnode = 4160361648, bytes_to_transfer = 65535, bytes_transfered = 0, fun_ptr = 0x0}
        res = <optimized out>
        j = <optimized out>
        task = 0x0
        pending_task = 0x0
        rank = 0
        __func__ = "_starpu_cpu_driver_run_once"
        continuation_wake_up = <optimized out>
        __PRETTY_FUNCTION__ = "_starpu_cpu_driver_run_once"
#6  0x0000fffff7e8a604 in _starpu_cpu_worker (arg=0xfffff7f05308 <_starpu_config+15960>) at drivers/cpu/driver_cpu.c:714
        worker = 0xfffff7f05308 <_starpu_config+15960>
        pi = {conf = 0x0, event_type = starpu_prof_tool_event_start_transfer, starpu_version = {1, 4, 4}, thread_id = -168038272, worker_id = 3, device_number = 3, driver_type = starpu_prof_tool_driver_cpu, memnode = 0, bytes_to_transfer = 0, bytes_transfered = 0, fun_ptr = 0x0}
#7  0x0000fffff786a394 in start_thread () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.
#8  0x0000fffff78cefdc in thread_start () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.

Thread 4 (Thread 0xfffff6fdf080 (LWP 102559)):
#0  0x0000fffff7868a88 in pthread_cond_broadcast@@GLIBC_2.17 () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.
#1  0x0000fffff7e15b8c in _starpu_worker_relax_on () at ./core/workers.h:1117
        p_ret = <optimized out>
        worker = 0xfffff7f03cf8 <_starpu_config+10312>
        __func__ = "_starpu_worker_relax_on"
        __PRETTY_FUNCTION__ = "_starpu_worker_relax_on"
#2  0x0000fffff7e16594 in ws_pop_task (sched_ctx_id=0) at sched_policies/work_stealing_policy.c:601
        ws = 0x428c30
        task = <optimized out>
        workerid = 1
        victim = <optimized out>
#3  0x0000fffff7e04f88 in _starpu_pop_task (worker=worker@entry=0xfffff7f03cf8 <_starpu_config+10312>) at core/sched_policy.c:1020
        sched_ctx = 0xfffff7fa1600 <_starpu_config+655696>
        task = 0x0
        worker_id = <optimized out>
        node = <optimized out>
        profiling = 0
        pop_start_time = {tv_sec = 281474841460248, tv_nsec = 0}
        pick = <optimized out>
        i = <optimized out>
        nbuffers = <optimized out>
#4  0x0000fffff7e2ab30 in _starpu_get_worker_task (worker=worker@entry=0xfffff7f03cf8 <_starpu_config+10312>, workerid=workerid@entry=1, memnode=memnode@entry=0) at drivers/driver_common/driver_common.c:431
        task = <optimized out>
        keep_awake = <optimized out>
        __func__ = "_starpu_get_worker_task"
#5  0x0000fffff7e8a1bc in _starpu_cpu_driver_run_once (cpu_worker=cpu_worker@entry=0xfffff7f03cf8 <_starpu_config+10312>) at drivers/cpu/driver_cpu.c:608
        memnode = 0
        workerid = 1
        pi = {conf = 0xfffff6fde760, event_type = 4143834912, starpu_version = {65535, 4143834848, 65535}, thread_id = -135748100, worker_id = 65535, device_number = -135250696, driver_type = 65535, memnode = 4160361648, bytes_to_transfer = 65535, bytes_transfered = 0, fun_ptr = 0xfffff7d9b0a8}
        res = <optimized out>
        j = <optimized out>
        task = 0x0
        pending_task = 0x0
        rank = 0
        __func__ = "_starpu_cpu_driver_run_once"
        continuation_wake_up = <optimized out>
        __PRETTY_FUNCTION__ = "_starpu_cpu_driver_run_once"
#6  0x0000fffff7e8a604 in _starpu_cpu_worker (arg=0xfffff7f03cf8 <_starpu_config+10312>) at drivers/cpu/driver_cpu.c:714
        worker = 0xfffff7f03cf8 <_starpu_config+10312>
        pi = {conf = 0x0, event_type = starpu_prof_tool_event_start_transfer, starpu_version = {1, 4, 4}, thread_id = -151129984, worker_id = 1, device_number = 1, driver_type = starpu_prof_tool_driver_cpu, memnode = 0, bytes_to_transfer = 0, bytes_transfered = 0, fun_ptr = 0x0}
#7  0x0000fffff786a394 in start_thread () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.
#8  0x0000fffff78cefdc in thread_start () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.

Thread 3 (Thread 0xfffff77ef080 (LWP 102558)):
#0  0x0000fffff7e165a8 in ws_pop_task (sched_ctx_id=0) at sched_policies/work_stealing_policy.c:602
        ws = 0x428c30
        task = <optimized out>
        workerid = 0
        victim = <optimized out>
#1  0x0000fffff7e04f88 in _starpu_pop_task (worker=worker@entry=0xfffff7f031f0 <_starpu_config+7488>) at core/sched_policy.c:1020
        sched_ctx = 0xfffff7fa1600 <_starpu_config+655696>
        task = 0x0
        worker_id = <optimized out>
        node = <optimized out>
        profiling = 0
        pop_start_time = {tv_sec = 281474841457424, tv_nsec = 0}
        pick = <optimized out>
        i = <optimized out>
        nbuffers = <optimized out>
#2  0x0000fffff7e2ab30 in _starpu_get_worker_task (worker=worker@entry=0xfffff7f031f0 <_starpu_config+7488>, workerid=workerid@entry=0, memnode=memnode@entry=0) at drivers/driver_common/driver_common.c:431
        task = <optimized out>
        keep_awake = <optimized out>
        __func__ = "_starpu_get_worker_task"
#3  0x0000fffff7e8a1bc in _starpu_cpu_driver_run_once (cpu_worker=cpu_worker@entry=0xfffff7f031f0 <_starpu_config+7488>) at drivers/cpu/driver_cpu.c:608
        memnode = 0
        workerid = 0
        pi = {conf = 0x0, event_type = starpu_prof_tool_event_driver_init_end, starpu_version = {1, 4152288992, 65535}, thread_id = -135748100, worker_id = 65535, device_number = -135253520, driver_type = 65535, memnode = 4160361648, bytes_to_transfer = 65535, bytes_transfered = 0, fun_ptr = 0x0}
        res = <optimized out>
        j = <optimized out>
        task = 0x0
        pending_task = 0x0
        rank = 0
        __func__ = "_starpu_cpu_driver_run_once"
        continuation_wake_up = <optimized out>
        __PRETTY_FUNCTION__ = "_starpu_cpu_driver_run_once"
#4  0x0000fffff7e8a604 in _starpu_cpu_worker (arg=0xfffff7f031f0 <_starpu_config+7488>) at drivers/cpu/driver_cpu.c:714
        worker = 0xfffff7f031f0 <_starpu_config+7488>
        pi = {conf = 0x0, event_type = starpu_prof_tool_event_start_transfer, starpu_version = {1, 4, 4}, thread_id = -142675840, worker_id = 0, device_number = 0, driver_type = starpu_prof_tool_driver_cpu, memnode = 0, bytes_to_transfer = 0, bytes_transfered = 0, fun_ptr = 0x0}
#5  0x0000fffff786a394 in start_thread () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.
#6  0x0000fffff78cefdc in thread_start () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.

Thread 2 (Thread 0xfffff67cf080 (LWP 102560)):
#0  _starpu_machine_is_running () at ./core/workers.h:588
        ret = <optimized out>
        ret = <optimized out>
#1  _starpu_get_worker_task (worker=worker@entry=0xfffff7f04800 <_starpu_config+13136>, workerid=workerid@entry=2, memnode=memnode@entry=0) at drivers/driver_common/driver_common.c:506
        task = <optimized out>
        keep_awake = <optimized out>
        __func__ = "_starpu_get_worker_task"
#2  0x0000fffff7e8a1bc in _starpu_cpu_driver_run_once (cpu_worker=cpu_worker@entry=0xfffff7f04800 <_starpu_config+13136>) at drivers/cpu/driver_cpu.c:608
        memnode = 0
        workerid = 2
        pi = {conf = 0x0, event_type = starpu_prof_tool_event_driver_init_end, starpu_version = {1, 4135380704, 65535}, thread_id = -135748100, worker_id = 65535, device_number = -135247872, driver_type = 65535, memnode = 4160361648, bytes_to_transfer = 65535, bytes_transfered = 0, fun_ptr = 0x0}
        res = <optimized out>
        j = <optimized out>
        task = 0x0
        pending_task = 0x0
        rank = 0
        __func__ = "_starpu_cpu_driver_run_once"
        continuation_wake_up = <optimized out>
        __PRETTY_FUNCTION__ = "_starpu_cpu_driver_run_once"
#3  0x0000fffff7e8a604 in _starpu_cpu_worker (arg=0xfffff7f04800 <_starpu_config+13136>) at drivers/cpu/driver_cpu.c:714
        worker = 0xfffff7f04800 <_starpu_config+13136>
        pi = {conf = 0x0, event_type = starpu_prof_tool_event_start_transfer, starpu_version = {1, 4, 4}, thread_id = -159584128, worker_id = 2, device_number = 2, driver_type = starpu_prof_tool_driver_cpu, memnode = 0, bytes_to_transfer = 0, bytes_transfered = 0, fun_ptr = 0x0}
#4  0x0000fffff786a394 in start_thread () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.
#5  0x0000fffff78cefdc in thread_start () from /gnu/store/a19xbynxc3sg25xpkwmx7g0mdl7g31hx-glibc-2.35/lib/libc.so.6
No symbol table info available.

Thread 1 (Thread 0xfffff7ff1020 (LWP 102544)):
#0  starpu_sched_ctx_create (workerids=0x0, nworkers=1, sched_ctx_name=sched_ctx_name@entry=0xfffff7ec0b48 "parallel_workers") at core/sched_ctx.c:793
        __func__ = "starpu_sched_ctx_create"
        varg_list = {__stack = 0xfffffffebbd0, __gr_top = 0xfffffffebbd0, __vr_top = 0xfffffffebba0, __gr_offs = -32, __vr_offs = 0}
        arg_type = -135262208
        min_prio_set = 0
        max_prio_set = 0
        min_prio = 0
        max_prio = 0
        nsms = 0
        sub_ctxs = 0x0
        nsub_ctxs = 0
        user_data = 0x0
        sched_policy = 0x0
        hierarchy_level = 0
        nesting_sched_ctx = 10
        awake_workers = 0
        init_sched = 0x0
        num_workers = 4
        i = 0
        sched_ctx = <optimized out>
        added_workerids = 0x42e070
        nw_ctx = <optimized out>
        p_ret = <optimized out>
        __ptrs = <optimized out>
        __n = <optimized out>
#1  0x0000fffff7e8c214 in _starpu_parallel_worker_create (parallel_worker=parallel_worker@entry=0x42c3b0) at parallel_worker/starpu_parallel_worker_create.c:333
        config = <optimized out>
#2  0x0000fffff7e8c3f4 in _starpu_parallel_worker_group_create (group=group@entry=0x42c2f0) at parallel_worker/starpu_parallel_worker_create.c:350
        c = 0x42c3b0
#3  0x0000fffff7e8d590 in _starpu_parallel_worker_config (parallel_worker_level=<optimized out>, machine=0x42c270) at parallel_worker/starpu_parallel_worker_create.c:553
        g = 0x42c2f0
        ret = 0
        config = <optimized out>
        sched_policy = <optimized out>
        global_ctx = <optimized out>
#4  0x0000fffff7e8d7ec in _starpu_parallel_worker_init_varg (parallel_worker_level=parallel_worker_level@entry=HWLOC_OBJ_PACKAGE, varg_list=...) at parallel_worker/starpu_parallel_worker_create.c:241
        arg_type = 0
        machine = 0x42c270
        __func__ = "_starpu_parallel_worker_init_varg"
        __PRETTY_FUNCTION__ = "_starpu_parallel_worker_init_varg"
#5  0x0000fffff7e8e058 in starpu_parallel_worker_init (parallel_worker_level=parallel_worker_level@entry=HWLOC_OBJ_PACKAGE) at parallel_worker/starpu_parallel_worker_create.c:255
        config = <optimized out>
        varg_list = {__stack = 0xfffffffebea0, __gr_top = 0xfffffffebea0, __vr_top = 0xfffffffebe60, __gr_offs = -56, __vr_offs = -128}
#6  0x0000000000400ff8 in main () at parallel_workers/parallel_workers.c:79
        ntasks = 8
        ret = 0
        i = <optimized out>
        parallel_workers = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        __func__ = "main"
        array1 = {0 <repeats 4000 times>}
        array2 = {0 <repeats 3000 times>, 1.3906711614409153e-309, 1.3906704974653626e-309, 1.3906711614411525e-309, 1.3906704983826054e-309, 0, 0, 1.3906711614613894e-309, 1.3906704975785234e-309, 1.3906704984230793e-309, 1.3906704983826054e-309, 1.3906704984275061e-309, 0, 1.0239368235597433e+200, 5.0130396337438505e-90, 8.3365299802249716e-72, 3.6195066075658384e+262, 1.1146009660511128e+171, 2.2120874227700783e+214, 1.1746884519525608e+214, 3.7879995910192795e+209, 1.1711897052348906e+166, 1.9108618774865702e+214, 3.5591190367735002e+180, 1.46016160971922e-319, 0 <repeats 377 times>, 7.7305068220971491e-318, 7.7112580245351742e-318, 7.7112580245351742e-318, 3.2379086165851934e-319, 0, 2.4703282292062327e-323, 8.034060754902011e-318, 8.1554823280239558e-318, 8.1439409545371042e-318, 8.3982464237645107e-318, 3.2379086165851934e-319, 7.7102698932434917e-318, 1.4821969375237396e-323, 0 <repeats 15 times>, 1.2142157312194475e-318, 1.2024767314742595e-318, 1.2024767314742595e-318, 0, 4.0473857707314917e-319, 3.860826582861837e-319, 3.860826582861837e-319, 1.3906711614580693e-309, 1.390670497321886e-309, 1.3906711614586226e-309, 1.3906704983969926e-309, 1.3906711614593341e-309, 1.3906704973289412e-309, 1.3906711614586226e-309, 4.9406564584124654e-323, 1.3906711614584645e-309, 1.3906704974401455e-309, 1.3906704982485357e-309, 2.3221085354538588e-322, 1.3906711614593341e-309, 1.3906704973293563e-309, 1.390671161459255e-309, 1.3906704973530912e-309, 1.390671161459255e-309, 1.3906704973666879e-309, 0, 0, 2.0733533996918329e-317, 1.3906711614622194e-309, 1.390671161459255e-309, 1.3906704973663124e-309, 1.3906704566746112e-309, 1.3906704983969926e-309, 0, 1.3906704982545041e-309, 1.3906704650931736e-309, 1.3906704983969926e-309, 0, 1.3906704982475476e-309, 1.3906704660645462e-309, 1.3906704983969926e-309, 1.3906711614611522e-309, 1.3906704973779723e-309, 2.0733533996918329e-317, 0, 1.3906704984275061e-309, 0, 4.9406564584124654e-324, 1.3906711614622194e-309, 1.3906704984028423e-309, 1.3906704983826054e-309, 0, 1.390670497266353e-309, 1.3906704983623685e-309, 1.3906711614622589e-309, 1.3906704650725415e-309, 1.3906711614622589e-309, 1.3906704650725415e-309, 9.8813129168249309e-324, 1.3906711614622589e-309, 1.3906711614590179e-309, 9.8813129168249309e-324, 0, 1.4821969375237396e-323, 1.3906704984253717e-309, 1.3906711614625751e-309, 0, 1.3906704984028423e-309, 2.9643938750474793e-323, 3.2127112686472898e-319, 5.2917543283166305e-318, 3.2127112686472898e-319, 5.2917543283166305e-318, 4.2440079518075883e-314, 0, 0, 0, 9.7773615049399326e-318, 2.0236928853657458e-320, 1.3906711614609941e-309, 1.3906704973765889e-309, 1.3906704572715759e-309, 0, 0, 8.4617375499254853e-315, 1.3906711614662115e-309, 1.3906704972666494e-309, 1.390671161470994e-309, 1.3906704984230793e-309, 1.390670464783849e-309, 1.3906704984275061e-309, 1.3906704982485357e-309, 4.9406564584124654e-324, 0, 1.3906711614712707e-309, 0, 1.390670497266353e-309, 0, 0, 0, 1.390670497266353e-309, 0, 1.3906704984324467e-309, 0, 0, 0, 4.9406564584124654e-323, 0, 0, 0, 6.9169190417774516e-323, 0, 0, 1.3906704982481405e-309, 1.3906711614820216e-309, 0, 4.1106261733991712e-321, 3.3280039514459023e-294, 0, 2.1279211652158202e-314, 7.9595951807608183e-319, 3.1620201333839779e-322, 9.7564921720595984e-318, 1.3350986381965695e-307, 1.8914248227666973e-307, 8.4879831668254831e-314, 3.1620201333839779e-322, 3.1620201333839779e-322, 3.1620201333839779e-322, 2.7667676167109806e-321, 2.7667676167109806e-321, 3.9525251667299724e-323, 8.4879831653432862e-314...}
        handle1 = 0x0
        handle2 = 0x0
        size = 0
        out = <optimized out>

Thread 5 (Thread 0xfffff5fbf080 (LWP 102561)):
Undefined command: "py-bt".  Try "help".
#Execution_time_in_seconds 0.286683 ./parallel_workers/parallel_workers
FAIL parallel_workers/parallel_workers (exit status: 1)
```

### Distribution

Debian 12 ARM

### Version of StarPU

Release 1.4.4 of StarPU available with Guix

**Comment by sthibaul** [comment]
Indeed, the test is looking for sockets, which macos doesn't expose to hwloc. I have added the error handling in https://gitlab.inria.fr/starpu/starpu/-/commit/b2b4f414ab9f916d3fa57328617fefc8a94d4a77 , that should be "fixing" the test by making it skip
